language: go
go:
- tip
gobuild_args: -x -ldflags "-X main.buildversion=$(git rev-parse HEAD)"
before_install:
- sudo apt-get install gcc-mingw-w64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64-i686
  binutils-mingw-w64-x86-64 ansible
- go get -u github.com/tools/godep
- go get github.com/go-playground/overalls
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
before_script:
- go vet
- go test -v ./...
script:
- overalls -project=github.com/NyaaPantsu/nyaa -covermode=count -debug  -- -race
- goveralls -coverprofile="coverage.txt" -service=travis-ci -repotoken $COVERALLS_TOKEN
install:
- export GOPATH="${TRAVIS_BUILD_DIR}/vendor:$GOPATH"
- export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
before_deploy:
- "./package.sh"
deploy:
  provider: releases
  api_key:
    secure: Nz2M3ZbQumKGVga/nnZnz1VXikRkGoLXk5FoH4uOl6GF6rlUNmtvJYs34LWF0/CMswBXNhjCggEaMMtZC+j66ZjoAdHBXRfrOb6jisNJRF6FNk7Kob6W3itCEOTvEL/8a+k2fI95cLqOXDLR2tIX03nchb8rDmVALs7P4gQgy2Y7UAo/aa/0G+OhsSJrlQWt0MT9OKGoIXpeKZjOG3wO/YwqfDwRTItuA9DLFoMQ0gwQfgT58t1ullbpM+jISni7rwfK+jUnZHjUH/VHLguVFmL4A1DxWriJXNOrZR+i/eUJ94mWvfI08WR8Qh3UCr58FrKoWvPsu7HnCq0bn6RvQtCKqx5zgv+R+kxKIP+79SVjKZUi1ghswAuwx9+AT6vHgPLXjJLpZj9Ap/KhfnQR6VT3jBT+kEpmv3J+57JcJCyD4ZslT+LGW2ul0uWoGCVVMBdHqMzuC8OSxpKCw6bFNWnLq+JAU08zlJkAAllBKev+LZWiF8GBICKfynRgViy+MKNaMfzIUNlL9UDskaiWP+BL9RXGLJ2FVdeKkzqdAYdYlgdJChQ56KTtRukR7FlOqDXhszIPxJhU9wn9lNXmGvq1FJyo1LRY3HX+5o9lWw+enaswNxFxdLBMXPhF5jehMkImiR4/YS4WdlmHcEfsli9sBOjBQh1iIpCfme77PPU=
  script:
  - "./package.sh"
  file: dist/*.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
env:
  global:
    secure: JHYFZn9q7kO+c0uN31AUxL2OqMe6wDbRVjLzH4/kcXv5pV9hrA/2lZaplN3hFIsLWz6Y0ZoFqvlGtq1gVj+E5TvrRQtEzHwM2O9sPB5VD5iVMNaHDmtOQTkNWg5Dn/tQtgNq9gagE7Kvl7MeNVuai7eAs79OB5j+Wl/JcrCRUliPqBRVZDBqh/pg7jfvdAkRABg7/zSl7uVZJ0jrcM8M8QfLt9/JFg62vYnT+hDqlqLYAZeQw9LUESi4zW68rFsFXNjHC4xq1EnZeqKK4OadkCGImhwa69Z1H+ZcbCoeC/RgUWEO/8bcBmXU1us4HXw5ouPWPW9rLRjJ2cwTgLBVSiHX6Y3oeLCtSepOCWTr4t9GnzcaI26G9tuphI7nXbqzlPu7PZm3XEEwP8YW0qg6yk/f77blJX5tbTr/NdHXATuqwzZWaHdlAtXfPQfbt5kGUBAxSWIBthNbrykPi3uJL9sbT25+nZt8hHRfrZ9hEcZO0WSXSLvUdbib7/Cv2e0Uks97cctzNbfiNwMQIQcegQ+y1GDA/BB6N+31RVMBSp8mcv+udEnm8ED6Kr8luJajOxsdWISpNp2GVoFJ/hn4W6+ENA3US4TOAXZLqOSOeOfeyuhAy9+sRjbbiDp5YHjyO+kE7FeQutuEbTwp9a1W7U3zb8bPW0Xvx8eDdZ6cgqg=
